name: unittests

on: [push, pull_request]

jobs:
  unittests:
    name: '[PHP ${{ matrix.php-versions }} | Flow ${{ matrix.flow-versions }}] Unit Tests'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [8.3]
        flow-versions: [8.3]

    env:
      FLOW_CONTEXT: Testing/Unit
      FLOW_DIST_FOLDER: flow-base-distribution

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions:  mbstring, xml, json, zlib, iconv, intl, pdo_sqlite, mysql
          ini-values: opcache.fast_shutdown=0

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}-flow-${{ matrix.flow-versions }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-versions }}-flow-${{ matrix.flow-versions }}-composer-
            php-${{ matrix.php-versions }}-flow-

      - name: Create composer.json
        run: composer create-project neos/flow-base-distribution ${{ env.FLOW_DIST_FOLDER }} --prefer-dist --no-progress --no-install "^${{ matrix.flow-versions }}"

      - name: "Allow neos composer plugin"
        run: composer config --no-plugins allow-plugins.neos/composer-plugin true
        working-directory: ${{ env.FLOW_DIST_FOLDER }}

      - name: Change version of neos/behat to @dev
        run: composer require "neos/behat:@dev" --dev --no-update
        working-directory: ${{ env.FLOW_DIST_FOLDER }}

      - name: Install composer dependencies
        run: composer install
        working-directory: ${{ env.FLOW_DIST_FOLDER }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.FLOW_DIST_FOLDER }}/DistributionPackages/Netlogix.WebApi

      - name: Install netlogix/webapi
        run: composer require netlogix/webapi:@dev
        working-directory: ${{ env.FLOW_DIST_FOLDER }}

      - name: Run tests
        run: bin/phpunit -c DistributionPackages/Netlogix.WebApi/phpunit.xml.dist --bootstrap "Build/BuildEssentials/PhpUnit/UnitTestBootstrap.php"
        working-directory: ${{ env.FLOW_DIST_FOLDER }}
